### ISSUE TITLE
Gyana Article on Tech Crunch

### ISSUE THREAD

**Issue by chivian** [khuyentran1401/machine-learning-articles#113]
## Key Takeaways
* 
* 

## Useful Code Snippets
```python
#Add your codes here
import numpy as np
import pandas as pd

```

## Useful Tools
* 
*

**Comment by khuyentran1401** [comment]
Hi Chinwe, thank you for your contribution! This article seems to focus more on the news rather than the technical side of data science. It would be nice to see the article that explains how to use this app instead. I will close this issue for you but you're welcome to contribute another article in the future
